# Generated by Django 5.1.4 on 2024-12-14 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('ressource', models.BinaryField(blank=True, null=True)),
                ('assignation', models.BinaryField(blank=True, null=True)),
                ('date_archive', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.niveau'),
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('administrateur', 'Administrateur'), ('professeur', 'Professeur'), ('etudiant', 'Etudiant'), ('chef_classe', 'Chef de Classe')], max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('niveau_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='ReleveDeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_cour', models.FloatField()),
                ('note_examen', models.FloatField()),
                ('moyenne', models.FloatField(default=0)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.matiere')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('general', 'General'), ('individuel', 'Individuel'), ('classe', 'Classe'), ('niveau', 'Niveau')], max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='programmes.utilisateur')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='programmes.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.utilisateur'),
        ),
        migrations.CreateModel(
            name='EspaceEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.niveau')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('titre_lesson', models.CharField(max_length=100)),
                ('contenu_lesson', models.TextField()),
                ('duree_faite', models.TimeField()),
                ('signature_prof', models.CharField(max_length=100)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('ressource', models.FileField(blank=True, null=True, upload_to='ressources/')),
                ('assignation', models.BinaryField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.niveau')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.salle')),
                ('modifie_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='CahierAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField()),
                ('date', models.DateField()),
                ('note_absence', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.emploidutemps')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.utilisateur')),
            ],
        ),
    ]
