# Generated by Django 5.1.4 on 2024-12-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_alter_utilisateur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
